### ISSUE TITLE
False 'Internet connection issue'

### ISSUE THREAD

**Issue by gerkus2** [ProtonVPN/protonvpn-cli#85] opened 2018-04-12 12:19 UTC
While using any form of connection: -c, -r, -f and --update; I get: 
[!] Error: There is an internet connection issue.
On --ip I get:
Error.
In the meantime, connecting by openvpn using provided config. files works just fine.

I'm using the latest version of raspbian on a Raspberry PI 3

**Comment by xilopaint** [comment] 2018-04-12 16:27
Please, tell us if the following command gives you any error:

```
wget --header 'x-pm-appversion: Other' --header 'x-pm-apiversion: 3' \
        --header 'Accept: application/vnd.protonmail.v1+json' \
        --timeout 6 -q -O /dev/stdout 'https://api.protonmail.ch/vpn/location' \
        | awk -F'"' '$2 == "IP" { print $4 }'
```

**Comment by mazen160** [comment] 2018-04-12 20:05
This means that your internet connection is:
1) Censored that disallows accessing `api.protonmail.ch`
2) Very slow that failed in connection check.

Please check your Internet access connection/speed.

**Comment by gerkus2** [comment] 2018-04-12 20:46
@xilopaint - I've tried it, no error
@mazen160 - 
1. I was able to ping it, so it seems fine
2. I just gave it a speedtest. Download 5.33 Mbps Upload 1.41 Mbps. Not the fastest, but should be usable...

**Comment by xilopaint** [comment] 2018-04-12 21:05
> @xilopaint - I've tried it, no error

So that command outputs your current IP?

**Comment by gerkus2** [comment] 2018-04-13 06:52
> @xilopaint So that command outputs your current IP?

The awk part of the command didn't quite catch and display anything int the command line, but that's of little consequence. The part that interests us the most works - it writes it to dev/stdout without any problems. It shows the correct ip, same as [https://www.ipleak.net/](https://www.ipleak.net/)

**Comment by xilopaint** [comment] 2018-04-13 07:16
> The awk part of the command didn't quite catch and display anything int the command line, but that's of little consequence.

No, it's not irrelevant. If you get no output for that command it's precisely the reason why you can't connect to the VPN.

**Comment by xilopaint** [comment] 2018-04-13 07:56
@gerkus2 could you remove the `awk` part and paste here your output with the response data changed to avoid identification?

**Comment by gerkus2** [comment] 2018-04-13 08:41
@xilopaint Seems like a correct response format:
{
    "Code": 1000,
    "IP": "94.254.xxx.xx",
    "Lat": xx.2394,
    "Long": xx.0362,
    "Country": "PL",
    "ISP": "Play"
}

**Comment by xilopaint** [comment] 2018-04-13 10:25
@gerkus2 yes, it's correct and should work. It seems your issue is with the `awk` command. It's weird. I ran that command in my Raspbian installation in a RPi 3 with no issues and got the IP as output.

What's your output for `which awk`?

**Comment by gerkus2** [comment] 2018-04-13 10:52
@xilopaint - /usr/bin/awk

**Comment by xilopaint** [comment] 2018-04-13 11:06
Please, now try:

`awk -W version` and `ls -l /usr/bin/awk` just to make sure you have the same setup as me.

**Comment by gerkus2** [comment] 2018-04-13 13:04
@xilopaint That's what I get:
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan
compiled limits:
max NF             32767
sprintf buffer      1020

**Comment by xilopaint** [comment] 2018-04-13 14:52
@gerkus2 you missed the `ls -l /usr/bin/awk` output.

**Comment by mazen160** [comment] 2018-04-14 21:45
@gerkus2 
Can you please do:
```bash
$ wget --header 'x-pm-appversion: Other' --header 'x-pm-apiversion: 3' \
        --header 'Accept: application/vnd.protonmail.v1+json' \
        --timeout 6 -q -O /dev/stdout 'https://api.protonmail.ch/vpn/location'

$ echo $?
```

and show us the output.

If it's your IP address, just redact part of it.

**Comment by mazen160** [comment] 2018-04-14 21:47
This should be an issue in your internet connection. I will mark it as closed, with your confirmation needed. It will be re-opened once you answer and provide the output.

Thanks,
Mazin

**Comment by xilopaint** [comment] 2018-04-14 22:51
> This should be an issue in your internet connection. I will mark it as closed, with your confirmation needed. It will be re-opened once you answer and provide the output.

How can it be the internet connection? He gets a proper response when removes the awk part as stated here:

> @xilopaint Seems like a correct response format:
> {
> "Code": 1000,
> "IP": "94.254.xxx.xx",
> "Lat": xx.2394,
> "Long": xx.0362,
> "Country": "PL",
> "ISP": "Play"
> }

**Comment by mazen160** [comment] 2018-04-15 21:00
@gerkus2 
This bug should be fixed. Please update and re-test it!

Best,
Mazin

**Comment by xilopaint** [comment] 2018-04-15 22:06
Wouldn't it be better to investigate what's the root cause of the issue before adopting Python in the `check_ip` function? The original code is working for me in the same platform and hardware of @gerkus2 (Raspbian Stretch in a Raspberry Pi 3).

**Comment by mazen160** [comment] 2018-04-15 22:31
@xilopaint 
Do you have the same `awk` version @gerkus2 is using?

Since python is a depency by default, it would be fine to use it in my opinion. Also, the response of the API is in JSON. Python should be much reliable solution for doing the parsing

**Comment by xilopaint** [comment] 2018-04-15 22:48
> @xilopaint
> Do you have the same awk version @gerkus2 is using?

Yes.

**Comment by mazen160** [comment] 2018-04-16 23:05
Hi all,

I pushed another fix that suppress errors and basically treats the python call as just normal commands. This should be the most accurate solution since `awk` was not parsing JSON as is; if the structure of the API response changes for example, it would break. Meanwhile, an actual JSON parser would be better to handle everything in the background. 

Thank you @xilopaint and everyone for the awesome work as always!!

Best,
Mazin

**Closed** 2018-04-16 23:06 UTC
Labels: Closed - User Confirmation Needed
