### ISSUE TITLE
sudo: protonvpn-cli: command not found with Solus distibution

### ISSUE THREAD

**Issue by flavienbonvin** [ProtonVPN/protonvpn-cli#12] opened 2018-03-22 07:07 UTC
The installation of the tool works fine with Solus but once the installation I get an error "sudo: protonvpn-cli: command not found" (even after a reboot). The file is copied to the "/usr/local/bin" folder but don't seems to work

**OS**: Solus x86_64
**OpenVPN**: 2.4.5
**sysctl**: 3.3.12
**python**: 3.6.4
**Dialog**: 1.3-20170131

**Comment by sotpapathe** [comment] 2018-03-23 19:53
The problem has to do with sudo, since it can be launched both without sudo and directly by the root user.

**Comment by mazen160** [comment] 2018-03-24 00:52
Hi  @flavienbonvin 
I have tested the issue, and protonvpn-cli installation seems to work normally on Solus. 

I have tested it now on clean instance. Probably checking your `$PATH` variable will indicate why it's not found. If /usr/local/bin/ is not in `PATH`, then this is an expected behaviour, the solution is to manually add the path.

**Comment by mazen160** [comment] 2018-03-24 00:53
Also @sotpapathe is a possible reason why you are encountering this behavior.

**Comment by mazen160** [comment] 2018-03-24 20:39
Hi @flavienbonvin 
I will be closing the ticket. If you're still encountering this issue. Please re-open the ticket or send me an email, and I will be glad to help.

Thanks,
Mazin

**Comment by flavienbonvin** [comment] 2018-03-24 21:14
@mazen160, the installation is fine for me too, but once it's installed I can't launch the command from the terminal.

The file (protonvpn-cli) is in the /usr/local/bin/ folder and I have this path in my $PATH variable. The command even come with the auto-completion (tab) in the terminal. But once I want to launch it it tells me it can't find the command.

If I launch from the folder (/usr/local/bin) it works just fine,

**Comment by mazen160** [comment] 2018-03-24 21:31
@flavienbonvin Can you try `which protonvpn-cli` to confirm? Also, can you try executing it in root?

**Comment by mazen160** [comment] 2018-03-24 21:35
@flavienbonvin I have installed a clean Solus image and tested your issue today. I can't seem to reproduce your report.

**Comment by flavienbonvin** [comment] 2018-03-24 21:43
Ok here are my results:
`which protonvpn-cli` give me : `/usr/local/bin/protonvpn-cli`
`sudo which protonvpn-cli` give me : `which: no protonvpn-cli in (/usr/sbin:/usr/bin:/sbin:/bin)`

To install the tool I have to execute is as root (`sudo ./protonvpn-cli.sh -install`) or it won't install.

If I launch the program:
`protonvpn-cli` I get the help of the program but if I try `protonvpn-cli -c` I get the message: `[!] Error: The program requires root access.`
Si I tried to launch it as sudo `sudo protonvpn-cli -c` and got `sudo: protonvpn-cli: command not found`

**Comment by sotpapathe** [comment] 2018-03-24 22:27
I have the same issue. I can find the protonvpn-cli script using `which` both from my normal user and root. Using `sudo which` however I get the same error as @flavienbonvin . I have also confirmed that the `PATH` variable for both my normal user and root contain `/usr/local/bin`. So I guess the issue is that `sudo` in Solus is compiled so that it doesn't check in `/usr/local/bin`. I guess the two possible solutions would be to either change the install directory to `/usr/bin` or file a bug report in Solus.

**Comment by mazen160** [comment] 2018-03-24 23:10
Hi @sotpapathe @flavienbonvin 

I checked more into this. 

```bash

solustest@solusbox ~ $ printenv PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/snap/bin
solustest@solusbox ~ $ sudo printenv PATH
/usr/sbin:/usr/bin:/sbin:/bin
solustest@solusbox ~ $ sudo su
root@solusbox /home/solustest # printenv PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/snap/bin
```

This seems to be definitely either a bug or a bad design by Solus.

Solution will be that it will be reported to Solus for input. Also, I will check about changing the path to /usr/bin/ instead. I have to confirm about changing the path.

**Comment by mazen160** [comment] 2018-03-25 08:59
A fix was pushed. Please check it, and let me know if it fixes the issue.

**Comment by flavienbonvin** [comment] 2018-03-25 09:03
@mazen160 thank you very much! everything works fine now

**Comment by mazen160** [comment] 2018-03-25 09:05
@flavienbonvin Awesom!!

**Closed** 2018-03-25 09:05 UTC
Labels: Closed - User Confirmation Needed
