### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by TApplencourt** [ProtonVPN/protonvpn-cli#90] opened 2018-04-15 23:40 UTC
I got this error message:

```
sudo protonvpn-cli -connect

Connecting...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[$] Connected!
[#] New IP: 185.94.189.187
```

This doesnt seem to impact the behavior of the VPN.

**Comment by xilopaint** [comment] 2018-04-16 02:09
I also got this error. It's kinda intermittent to me. This issue was introduced by e4d68567955808c5b066fd72a67386c15959517a.

This change is intended to fix #85, which couldn't be reproduced. The previous `awk` command looks much cleaner to me. I vote for reverting the commit unless we can confirm an issue with `awk` in any distro.

**Comment by mazen160** [comment] 2018-04-16 09:58
Confirmed. I will fix this

**Comment by mazen160** [comment] 2018-04-16 22:59
Hi,

This bug should be fixed now :)

**Closed by mazen160** 2018-04-16 22:59 UTC

**Comment by xilopaint** [comment] 2018-04-17 01:11
But it doesn't fix the bug, it just suppress the error...

**Comment by mazen160** [comment] 2018-04-17 01:13
@xilopaint Nope, if the response is empty `""`, then the IP checking failed, if it failed 3 times, then there is an internet connection issue :)

**Comment by mazen160** [comment] 2018-04-17 01:26
Yup exactly!, which is weird, but it's fine as long it's working now :D

**Comment by xilopaint** [comment] 2018-04-17 01:32
It's not exactly "working", you just suppressed the error. Since the `check_ip()` function tries to get the IP three times the code only "works" if that exception is not raised in the other two attempts and the response is not empty. You are basically wasting one of the three attempts with your change in the code that suppress the error instead of fix it properly by skiping the BOM.

**Comment by xilopaint** [comment] 2018-04-17 02:08
> @xilopaint Nope, if the response is empty "", then the IP checking failed, if it failed 3 times, then there is an internet connection issue :)

Just to be clearer. If you don't fix the issue the users will fail to connect and see your custom internet connection error in some occasions in which they have a proper API response.

**Comment by mazen160** [comment] 2018-04-17 02:11
it works as the following:
```
ip = ""
while ip is empty() and counter > 3:
  ip = get_ip()
  counter+= 1
  if counter> 3:
   ip = "Error."
print(ip)
```

This is a pseudocode of the function. 

If there is an exception in parsing, then there is an error in retrieving, in both cases, the response will be empty if failed. 

If succeed, it will return the IP address.

**Comment by xilopaint** [comment] 2018-04-17 02:30
If you skip the BOM you will not have the Python exception, so you will not have an error in retrieving the IP. That exception does not mean you don't have a proper response, it means you have a BOM that could not be decoded. If you skip the BOM you can retrieve the IP and your connection will succeed.

**Comment by xilopaint** [comment] 2018-04-17 07:29
Hey, @mazen160. Sorry for the confusion, I realised that the error in e4d68567955808c5b066fd72a67386c15959517a was not related to BOM, but a mistake in the ternary operator.

This was how you wrote the Python code:

`import json; _ = open("/dev/stdin", "r").read(); _ if len(_) > 0 else "{\"IP\" : \"\"}"; print(json.loads(_)["IP"])`

That has no effect because you didn't assign a value for `_` on the ternary operator, you're just returning `_` or ` "{\"IP\" : \"\"}"` with no assignment. So the print function will fail when the response is empty because the value of `_` is unchanged and thus invalid json.

You should do this:

`import json; _ = open("/dev/stdin", "r").read(); _ = _ if len(_) > 0 else "{\"IP\" : \"\"}"; print(json.loads(_)["IP"])`

Or even better and cleaner:

`import json; _ = open("/dev/stdin", "r").read(); print(json.loads(_)["IP"]) if _ else None`

With this solution you don't need to redirect stderr to `/dev/null` since the print function will only be called when the response is not empty.

**Comment by mazen160** [comment] 2018-04-17 18:53
@xilopaint  Nice! but I can get you scenarios that can gets an exception in this part

1) wget output is not json - response related
2) something is done wrong with machine that blocks connections, then returning invalid json response

To avoid all that, treating python as a tool would be the most efficient part, then redirecting stderr to `/dev/null`
